<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>de20fef2-fe26-4796-a534-d5e812b76ef6</testSuiteGuid>
   <testCaseLink>
      <guid>ea47f73e-8699-4786-ad2f-46d660b92914</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriveTest/ValidLogin2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3c22dcc6-8b80-4333-aada-ce3daa52a4d5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3c22dcc6-8b80-4333-aada-ce3daa52a4d5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>b24505d9-938e-484b-b08b-961811213cdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3c22dcc6-8b80-4333-aada-ce3daa52a4d5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>7469431a-c1d7-4bad-988b-03ffb4585371</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
